<?php

namespace MS\GestionBibliothequeBundle\Repository;

use MS\GestionBibliothequeBundle\Entity\Adherent;

/**
 * AdherentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdherentRepository extends \Doctrine\ORM\EntityRepository {
    
    public function findOwnEmprunts(Adherent $adherent) {
        $qb = $this->createQueryBuilder('ad');
        $qb->innerJoin('ad.emprunts', 'emp')->addSelect('emp');
        $qb->andWhere('emp.adherent = :adherent')->setParameter('adherent', $adherent);
        return $qb
        ->getQuery()
        ->getResult()
        ;
    }
    
}
